### ISSUE TITLE
怎么改授权地址呢？

### ISSUE THREAD

**Issue by xonec** [aazooo/zjmf#69]
魔方云KVM加强版

环境要求

1、必须安装在全新的服务器上：TencentOS Server3.1已验证TencentOS-Server-3.1-TK4-x86_64-everything版本；centos7.9请使用 yum update 将系统更新至最新版，centos8stream不需要执行 dnf update 更新系统命令

2、系统：确保是干净的操作系统，没有安装过其它环境（已有环境不可安装）；主控（Web面板）建议使用TencentOS Server3.1、CentOS 8 stream（强烈建议）、CentOS 7.9；计算节点（生产KVM的母鸡）建议使用TencentOS Server3.1、centos 8 stream（强烈建议）、CentOS 7.9

**Comment by xonec** [comment]
# 请选择将要安装的系统: 3
4
.
# 系统环境                  要求                            当前
# 
#                  CentOS(7.8/8-Steram)      
# 系统版本           TencentOS Server(3.1)    tencentos 3.1 
#                  FusionOS 22                
#                  Kylin v10                
# 
# Selinux           关闭          已关闭
# 
# /分区剩余容量     >10GB          42GB
# /home分区剩余容量 >10GB          42GB
# 
# 内核版本          >4.1          5.4.119
# 
# 网络连接           支持      授权服务器连接失败

# 授权服务器连接失败, 请确认网络是否联通, 或测试curl -s http://154.7.178.154////////////////app/api/ip 是否正常?

# 请根据以上信息, 配置安装环境. 然后重新执行本脚本.

**Comment by xmlgrg** [comment]
为何要去访问 http://154.7.178.154////////////////app/api/ip  这个地址呢？
